config/routes.rb
Meal::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => :sessions }	
  resources :admins
  resources :subscription_types do
    member do
      get :filter_subscriptions
    end
    collection do
      get :working_days_in_month
    end
  end
  resources :subscriptions do
    collection do
      put :update_payment_status
    end
  end
  resources :holidays

  devise_for :users, :controllers => { :sessions => :sessions }
  resources :users
  resources :transfers do
    member do
      put :update_payment_status
      put :cancel_borrow
    end
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match '/home' => "users#show"
  match "/admin" => redirect("/admins/signin")
  
end

app/views/admins/_subscription_list.html.erb
<p>
  <%= type_name = I18n.localize(subscription_type.month, :format => "%B-%Y") %> Subscriptions
</p>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Month</th>
      <th>User</th>
      <th>Payment Status</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% subscription_type.subscriptions.each do |subscription| %>
      <tr>
        <td><%= type_name  %></td>

        <td><%= subscription.user.fullname %></td>
        <td><%= payment_status(subscription) %></td>
        <td>
          <% unless subscription.payment_status %>
            <%= link_to "Payment Recieved", update_payment_status_subscriptions_path(:id => subscription.id, :s_type_id => subscription_type.id), :method => :put, :class => "btn btn-success", :remote => true %>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admins/_today_transfers.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Lender</th>
      <th>Booking Status</th> 
      <th>Borrowed By </th>  
    </tr>
  </thead>
  <% @todays_transfers.each do |transfer| %>
    <tr>
      <td><%= transfer.user.fullname %></td>
      <% if transfer.booking_status == false %>
        <td> Available </td>
        <td></td>
      <% else %>
        <td> Booked </td>
        <td> <%= transfer.borrower_name %> </td>
      <% end %> 
    </tr>
  <% end %>
</table>

app/views/admins/index.html.erb
<h4> Subscription Statistics</h4>
<% if @stypes.blank? %>
  <div class="well">
    <strong>
      No Subscription slots are available. Please create one subscription slot
      <%= link_to "here", subscription_types_path() %>
    </strong>
  </div>
<% else %>
  <div class="well">
    <strong>Select Subscription Slot in the select box to get the statistics.</strong>
    <div class="btn-group pull-right">
      <a class="btn dropdown-toggle btn-success stype-select-container" data-toggle="dropdown" href="#">
        <span class="caret pull-right"></span>
        <span id="stype-title">Choose Slot</span>
      </a>
      <ul class="dropdown-menu">
        <% @stypes.each do |type| %>
          <li>
            <%= link_to I18n.localize(type.month, :format => "%B-%Y"), filter_subscriptions_subscription_type_path(type), :class => "stype-list", :tabindex => "-1", :remote => true %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div id="stype-container">
    <% if @current_subscription_type %>
      <%= render :partial => "admins/subscription_list", :locals => {:subscription_type => @current_subscription_type} %>
    <% end %>
  </div>
<% end %>


<h4>
  Today's Transfers  (<%= I18n.localize(Date.today, :format => '%d %B %Y') %>)
</h4>
<%= render :partial => "admins/today_transfers" %>


<script type="text/javascript">
$(document).ready(function(){
  $(".stype-list").live("click", function(){
    $("#stype-title").text($(this).text());
  });
});
</script>

app/views/admins/show.html.erb
Welcome Admin !!