config/routes.rb
Meal::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => :sessions }	
  resources :admins
  resources :subscription_types do
    member do
      get :filter_subscriptions
    end
    collection do
      get :working_days_in_month
    end
  end
  resources :subscriptions do
    collection do
      put :update_payment_status
    end
  end
  resources :holidays

  devise_for :users, :controllers => { :sessions => :sessions }
  resources :users
  resources :transfers do
    member do
      put :update_payment_status
      put :cancel_borrow
    end
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match '/home' => "users#show"
  match "/admin" => redirect("/admins/signin")
  
end

app/models/user.rb
require 'getdetails'
class User < ActiveRecord::Base

  has_and_belongs_to_many :subscription_types
  has_many :subscriptions, :dependent => :destroy
  has_many :daily_transfers, :foreign_key => :lender_id, :dependent => :destroy
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :ldap_authenticatable, :rememberable, :trackable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :login, :password, :password_confirmation, :remember_me, :firstname

  before_save :get_ldap_email
  before_save :get_ldap_firstname
  before_save :get_ldap_fullname
  before_save :get_ldap_phone

  def has_currently_subscribed?
    self.current_subscription.present?
  end

  def has_subscribed_next_month?
    self.next_subscription.present?
  end

  def current_subscription
    subscr_type = SubscriptionType.current_subscription_type
    return nil if subscr_type.nil?
    subscriptions.where(:subscription_type_id => subscr_type.id).first
  end

  def next_subscription
    subscr_type = SubscriptionType.next_subscription_type
    return nil if subscr_type.nil?
    subscriptions.where(:subscription_type_id => subscr_type.id).first
  end

  def transfered_today_meal?
    self.daily_transfers.find_by_date(Date.today).present?
  end
  
  def get_todays_transfer
    self.daily_transfers.find_by_date(Date.today)
  end

  def get_borrower_name
    self.daily_transfers.find_by_date(Date.today).borrower_name
  end

  def has_borrowed_today?
   transfer = DailyTransfer.where(:borrower_id => self.id, :date => Date.today).first
   transfer.nil? ? false : true
  end
  
  def has_paid?
    self.current_subscription.payment_status
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
	def show
		@s_type_next = SubscriptionType.next_subscription_type
		@s_type_current = SubscriptionType.current_subscription_type
		@current_subscription = current_user.current_subscription if current_user.has_currently_subscribed?
		@next_subscription = current_user.next_subscription || Subscription.new
    @transfer = DailyTransfer.new
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_available_slots.html.erb
<div style = "float:right; margin-bottom: 20px;">
  <%= link_to('Show All Slots',"#", :id =>'all-slots-button') %>
</div>

<%= render :partial => "users/transfers_index", :locals => {:transfers => DailyTransfer.available_slots.all} %>

app/views/users/_subscribenow.html.erb
<div style = "float:right"> 
	<h2>Year 2013</h2>
    <table class="table table-striped">
		<thead>
			<tr>
				<th> Month </th>
				<th> No.of Working days </th>
				<th> Amount (in Rs) </th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td> January </td>
				<td> 22 </td>
				<td> 990 </td>
			</tr>
			<tr>	
				<td> February </td>
				<td> 20 </td>
				<td> 900 </td>
			</tr>
			<tr>
				<td> March </td>
				<td> 19 </td>
				<td> 855 </td>
			</tr>
			<tr>
				<td> April </td>
				<td> 21 </td>
				<td> 945 </td>
			</tr>
			<tr>
				<td> May </td>
				<td> 23 </td>
				<td> 1035 </td>
			</tr>
			<tr>
				<td> June </td>
				<td> 20 </td>
				<td> 900 </td>
			</tr>
			<tr>
				<td> July </td>
				<td> 23 </td>
				<td> 1035 </td>
			</tr>
			<tr>
				<td> August </td>
				<td> 21 </td>
				<td> 945 </td>
			</tr>
			<tr>
				<td> September </td>
				<td> 20 </td>
				<td> 900 </td>
			</tr>
			<tr>
				<td> October </td>
				<td> 21 </td>
				<td> 945 </td>
			</tr>
			<tr>
				<td> November </td>
				<td> 21 </td>
				<td> 945 </td>
			</tr>
			<tr>
				<td> December </td>
				<td> 21 </td>
				<td> 945 </td>
			</tr>
		</tbody>
	</table>
</div>
<div class = "container" >
<h4> List of holidays 2013 ></h4>
<ul style = "list-style-type:none" />
<li> January 14 - Pongal </li>
<li> January 26 - Republic day </li>
<li> March 27 - Holi </li>
<li> March 29 - Good Friday </li>
<li> April 11 - Ugadi </li>
<li> August 15 - Independence Day </li>
<li> September 9 - Vinayakar chathurthi </li>
<li> October 2 - Gandhi Jayanthi </li>
<li> October 14 - Vijayadasami </li>
<li> November 3 - Deepavali </li>
<li> December 25 - Christmas </li>
</div>

app/views/users/_subscription_status.html.erb
<div class = "row-fluid">
  <div class = "span6">
    <div class = "well" style = "height:175px;">
      <h5> <u>Current Subscription</u> (<%= @s_type_current.month.strftime('%b %Y') %>) </h5>
      <% if @current_subscription %> 
        <% if @current_subscription.payment_status == true %>
          <h5>Your subscription is active</h5>
        <% elsif @current_subscription.payment_status == false %>
          <div class="alert alert-error">
            <p> <strong>  Warning!!! </strong>Your subscription is not yet confirmed!!! </p>
          </div>
          <h5>Please <a href = "javascript:void(0)" rel = "tooltip" title = "Pay by cash to Mr. Murari Rao" data-placement = "bottom" > Pay </a>  &#x20B9;<%= @current_subscription.total_amount %>/- immediately to confirm your subscription </h5>
          <%= link_to('Cancel Subscription', subscription_path(@current_subscription),:method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to cancel?") %>
        <% end %>
      <% else %>
        <h5> You haven't subscribed for <%= Date.today.strftime('%B %Y') %> </h5>
      <% end %>
    </div>
  </div>
  <div class = "span6">
    <div class = "well" style = "height:175px;">
      <h5><u> Subscription for next month</u> (<%= @s_type_next.month.strftime('%b %Y') %>)  </h5>
      <% if !@next_subscription.new_record? %>
        <% if @next_subscription.payment_status == false %>
          <div class="alert alert-block">
            <p> <strong>  Warning!!! </strong>Your subscription is not yet confirmed!!! </p>
          </div>
          <h5>Please <a href = "javascript:void(0)" rel = "tooltip" title = "Pay by cash to Mr. Murari Rao" data-placement = "bottom" > Pay </a>  &#x20B9;<%= @next_subscription.total_amount %>/- to confirm your subscription </h5>
          <%= link_to('Cancel Subscription', subscription_path(@next_subscription),:method => :delete, :class => "btn btn-danger", :confirm => "Are you sure you want to cancel?") %>
        <% else %>
          <h5>Your subscription for <%= @next_subscription.subscription_type.month.strftime('%B %Y')%> is active</h5>
        <% end %>
      <% elsif @s_type_next %>
        <h5> Subscribe for <%= Date.today.next_month.strftime('%B %Y') %> </h5>
        <%= form_for (@next_subscription), :html => {:method => :post, :class => "form-horizontal modal-form", :remote => true} do |f| %>
          <%= f.hidden_field :subscription_type_id, :value => @s_type_next.id %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :total_amount, :value => @s_type_next.amount_per_day * @s_type_next.number_of_days %>
          <p> Total Amount: &#x20B9;<%= @s_type_next.amount_per_day * @s_type_next.number_of_days %>/- </p>
          <%= f.submit "Subscribe", :class => "btn btn-success", :id => "subscribe-submit" %>
          <%= image_tag "loading.gif", :id => "subscription-spinner-button", :style => "display: none;" %>
        <% end %>
      <% else %>
        <h5> Sorry.. the planner is not ready with the subscription for <%= Date.today.next_month.strftime('%B %Y') %>  </h5> 
      <% end %> <br/> 
    </div>
  </div>
</div>

app/views/users/_todays_transfers.html.erb
<div style = "float:right; margin-bottom: 20px;">
  <%= link_to('Show Available Slots',"#", :id =>'available-slots-button') %>
</div>

<%= render :partial => "users/transfers_index", :locals => {:transfers => DailyTransfer.todays_transfer.all} %>

app/views/users/_transfer_details.html.erb
<% unless current_user.transfered_today_meal? %>
  <%= form_tag transfers_path(), :method => :post, :class => "form-horizontal modal-form", :remote => true do %>
      <%= hidden_field_tag :subscription_id, current_user.current_subscription.id %>
      <%= hidden_field_tag :lender_id, current_user.id %>
      <%= hidden_field_tag :date, Date.today %>
      <%= submit_tag "Transfer Today's Meal", :id => "transfer-button" ,:class => "btn btn-success", :confirm => "Are you sure you want to transfer your meal?" %> 
  <% end %>
<% end  %>

app/views/users/_transfers_index.html.erb
<%= Date.today.strftime("%d %B %Y") %>

<table class="table table-bordered table-hover">

  <thead>
    <tr>
      <th>Lender</th>
      <th>Borrowed By </th>  
      <th>Action</th> 
    </tr>
  </thead>

  <% transfers.each do |t| %>  
    <tr>
      <td><%= lender_name(t) %></td>
      <td><%= booking_status(t) %></td>
      <% if t.payment_status == true %>
        <td>Recieved Amount</td>
      <% elsif @current_subscription && current_user.has_paid?  %>
        <% if t.lender_id == current_user.id && t.booking_status == true %>
          <% if t.payment_status == false %>
            <td>
              <%= form_tag update_payment_status_transfer_path(current_user.get_todays_transfer), :method => :put, :class => "form-horizontal modal-form"   , :id => "payment_recieved_form", :remote => true do %>
                <%= submit_tag "Received Payment", :class => "btn btn-success", :id => "received-payment-submit" %>
                <%= image_tag "loading.gif", :id => "received-payment-spinner-button", :style => "display: none;" %> 
              <% end %>
            </td>
          <% end %>
        <% else %>
          <td>Yet to be booked </td>
        <% end %>
      <% elsif current_user.has_borrowed_today? %>
        <% if t.borrower_id == current_user.id && t.payment_status == false %>
          <td>  
            <%= form_tag cancel_borrow_transfer_path(t), :method => :put, :class => "form-horizontal modal-form" ,:remote => true do %>
                <%= submit_tag "Cancel", :class => "btn btn-danger", :confirm => "Are you sure you want to cancel?" %>
            <% end %> 
          </td>
        <% else %>
          <td> You have already Borrowed</td>
        <% end %>
      <% else %>
        <td>
          <%= form_tag transfer_path(t), :method => :put, :class => "form-horizontal modal-form", :id => "borrow_form",:remote => true do %>
            <%= submit_tag "Borrow", :class => "btn btn-success",:id=> "borrow-submit", :confirm => "Are you sure you want to borrow?"%> 
            <%= image_tag "loading.gif", :id => "borrow-spinner-button", :style => "display: none;" %>
          <% end %>
        </td>
      <% end %>
    </tr>
  <% end %>  
</table>

app/views/users/index.html.erb
<h2>Welcome to Meals Planner Application</h2>

<p>Hello , Here is a simple app for your meals subscription...</p>

app/views/users/show.html.erb
<div class = "container" >
  <h4> Subscriptions   <div style = "float:right;">
    <%= link_to('View All My Subscriptions', subscriptions_path, :method => :get, :class => "btn") %>
  </div> </h4> <br/>

  <div id="subscription-container">
    <%= render :partial => "users/subscription_status" %>
  </div>
  
  <h4> Transfers 
  <div style= "float:right; margin-left:10px;">  
      <%= link_to(' View All My Transfers', transfers_path, :method => :get, :class => "btn") %>
    </div> 
    <div id = "transfer-details-button" style = "float:right;">
      <% if @current_subscription && current_user.has_paid? %> 
        <%= render :partial => "users/transfer_details" %>  
      <% end %>
    </div>
    
  </h4> 
  <br/>
  
  <div id="today_transfer" class="well" >
    <% if DailyTransfer.todays_transfer.empty? %>
      <h5>Sorry! there are no available meals today </h5>
    <% else %>
      <%= render :partial => "transfers/transfers_content" %>
    <% end %>
  </div>
</div>

app/views/users/subscriptions.html.erb
<div class = "well">
  <p style="margin-top: 50px;">
    List of all Subscriptions:
  </p>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Month</th>
        <th>Total Amount</th>
        <th>Payment status</th>
      </tr>
    </thead>
  <% current_user.subscriptions.all.each do |subs| %>
    <tr>
      <td><%= subs.subscription_type.month  %></td>
      <td>&#x20B9; <%= subs.total_amount%></td>
      <% if subs.payment_status == false %>
        <td> Not paid </td>
        <% else %>
        <td> Paid </td>
      <% end %>
    </tr>
    <% end %>
  </table>
</div>