config/routes.rb
Meal::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => :sessions }	
  resources :admins
  resources :subscription_types do
    member do
      get :filter_subscriptions
    end
    collection do
      get :working_days_in_month
    end
  end
  resources :subscriptions do
    collection do
      put :update_payment_status
    end
  end
  resources :holidays

  devise_for :users, :controllers => { :sessions => :sessions }
  resources :users
  resources :transfers do
    member do
      put :update_payment_status
      put :cancel_borrow
    end
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match '/home' => "users#show"
  match "/admin" => redirect("/admins/signin")
  
end

app/controllers/subscription_types_controller.rb
class SubscriptionTypesController < ApplicationController
  before_filter :authenticate_admin!

  def create
    @s_type = SubscriptionType.new(params[:subscription_type])
    @s_type.save
    #UserMailer.delay.new_subscription_type_email
    #UserMailer.new_subscription_type_email.deliver
    get_stypes
  end

  def index
    @s_type = SubscriptionType.new
    get_stypes
  end

  def edit
    @stype = SubscriptionType.find(params[:id])
  end

  def update
    @stype = SubscriptionType.find(params[:id])
    @stype.update_attributes(params[:subscription_type])
    get_stypes
  end

  def destroy
    type = SubscriptionType.find(params[:id])
    type.destroy
    get_stypes
  end

  def filter_subscriptions
    @s_type = SubscriptionType.find(params[:id])
  end

  def working_days_in_month
    @no_of_days = SubscriptionType.working_days_in_month(params[:date])
  end

  private

  def get_stypes
    @stypes = SubscriptionType.all
  end
end

app/helpers/subscription_types_helper.rb
module SubscriptionTypesHelper
end

app/views/subscription_types/_edit_form.html.erb
<form id="stype-form-<%= stype.id %>">
  <td>    
    <input class="uneditable-input" id="date-field-<%= stype.id %>" name="subscription_type[month]" type="text" value='<%= I18n.localize(stype.month, :format => "%d-%m-%Y") %>'/>
  </td>
  <td>
    <input name="subscription_type[number_of_days]" type="text" value="<%= stype.number_of_days %>" />
  </td>
  <td>
    <input name="subscription_type[amount_per_day]" type="text" value="<%= stype.amount_per_day %>" />
  </td>
  <td><%= stype.subscriptions.count %></td>
  <td>
    <input class="btn btn-success" id="stype-update-<%= stype.id %>" name="commit" type="submit" value="Update" />
    <a href="javascript:void(0)" class="btn cancel-update">Cancel</a>
  </td>
</form>

<script type="text/javascript">
$(document).ready(function(){
  $('.cancel-update').live('click', function(){
    $('.stype-form').hide();
    $('.stype-row').show();
  });

  $('#stype-update-' + '<%= stype.id %>').live('click', function(){
    $.ajax({
      type: "PUT",
      dataType: "script",
      url: '<%= subscription_type_path(stype) %>',
      data: $('#stype-form-' + '<%= stype.id %>').serialize()
    });
    return false;
  });
});
</script>

app/views/subscription_types/_form.html.erb
<div class="modal overlay" id="addSubType" role="dialog" aria-labelledby="myModalLabel" style="display: none;">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">x</button>
    <h3 id="myModalLabel">Add Subscription Slot</h3>
  </div>
  <%= form_for @s_type, :html => {:method => :post, :class => "form-horizontal modal-form", :remote => true} do |f| %>
    <div class="modal-body">
      <div class="alert" id="sub-type-errors" style="display: none;">
          
      </div>
      
      <div class="control-group">
        <%= f.label :month, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :month, :class => "date-field uneditable-input" %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :amount_per_day, "Amount per day", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :amount_per_day, :value => @s_type.amount_per_day %>
        </div>
      </div>
      <div class="control-group">
        <%= f.label :number_of_days, "No. of Days", :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :number_of_days, :value => @s_type.number_of_days %>
        </div>
      </div>
    </div>

    <div class="modal-footer">
      <button class="btn" data-dismiss="modal" aria-hidden="true">Close</button>
      <%= f.submit "Add Type", :class => "btn btn-primary", :id => "add-income-btn" %>
    </div>
  <% end %>
</div>

<script type="text/javascript">
$(document).ready(function(){  
  $("#subscription_type_month").live ("change", function(){   
    var date = Date.parse($(this).val());
    if (date === NaN)
      $("#subscription_type_number_of_days").val('0');
    else
      $.ajax({
        type: "GET",
        dataType: "script",
        url: '<%= working_days_in_month_subscription_types_path() %>',
        data: { date: $(this).val() },
      })
  });
});
</script>

app/views/subscription_types/_index_list.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Month</th>
      <th>No.of Days</th>
      <th>Amount per Day</th>
      <th>No of users subscribed</th>
      <th>Actions</th>
    </tr>
  </thead>
  <% stypes.each do |type| %>
    <tr id='<%= "stype-row-#{type.id}" %>' class="stype-row">
      <td><%= I18n.localize(type.month, :format => "%B-%Y") %></td>
      <td><%= type.number_of_days %></td>
      <td>&#8377; <%= type.amount_per_day %></td>
      <td><%= type.subscriptions.count %></td>
      <td>
        <%= link_to "Edit", edit_subscription_type_path(type), :class => 'btn btn-success', :remote => true %>
        <%= link_to "Delete", subscription_type_path(type), :class => 'btn btn-danger', :method => :delete, :remote => true, :confirm => "Are you sure to delete?" %>
      </td>
    </tr>
    <tr id='<%= "stype-#{type.id}-form" %>' style="display: none;" class="stype-form">
      <%= render :partial => "subscription_types/edit_form", :locals => {:stype => type} %>
    </tr>
  <% end %>
</table>

app/views/subscription_types/index.html.erb
<h4>
   Add new Subscription Slot
</h4>
<div class="well">
  <a href="#addSubType" data-toggle="modal" class="btn btn-success">Add Subscription Slot</a>
  <div style="float: right;">
  </div>
</div>

<h4 style="margin-top: 50px;">
  List of all Subscription Slots
</h4>

<div id="stype-container">
  <%= render :partial => 'subscription_types/index_list', :locals => {:stypes => @stypes} %>
</div>

<% content_for :popup do %>
  <%= render :partial => "subscription_types/form" %>
<% end %>

app/views/subscription_types/new.html.erb
<%= render :partial => 'subscription_types/form' %>