config/routes.rb
Meal::Application.routes.draw do
  
  devise_for :admins, :controllers => { :sessions => :sessions }	
  resources :admins
  resources :subscription_types do
    member do
      get :filter_subscriptions
    end
    collection do
      get :working_days_in_month
    end
  end
  resources :subscriptions do
    collection do
      put :update_payment_status
    end
  end
  resources :holidays

  devise_for :users, :controllers => { :sessions => :sessions }
  resources :users
  resources :transfers do
    member do
      put :update_payment_status
      put :cancel_borrow
    end
  end
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  match '/home' => "users#show"
  match "/admin" => redirect("/admins/signin")
  
end

app/views/layouts/_adminnavigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" >
  <div class="navbar-inner">  
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="#" style = "margin-left:10px"> MEALS PLANNER </a>
    <div class="nav-collapse collapse">
      <ul class="nav" style = "width:1035px;">
        <li class="<%= ['subscription_types', 'holidays'].include?(params[:controller]) ? '' : 'active' %>">
          <%= link_to 'Home', admins_path() %> 
        </li>
        <li class="<%= params[:controller].eql?('subscription_types') ? 'active' : '' %>">
          <%= link_to 'Subscription Slots', subscription_types_path() %>
        </li>
        <li class="<%= params[:controller].eql?('holidays') ? 'active' : '' %>">
          <%= link_to 'Holidays', holidays_path() %>
        </li>
        <li style="float:right">
          <%= link_to 'Logout', destroy_admin_session_path, :method => :delete %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <%= link_to "Home", user_path, :class => 'brand' %>
  <% if user_signed_in? %>
    <li>
    <%= link_to('Logout', destroy_user_session_path, :method=>'delete') %>        
    </li>
  <% else %>
    <li>
    <%= link_to('Login', new_user_session_path)  %>  
    </li>
  <% end %>
 
</ul>

app/views/layouts/_usernavigation.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" >
  <div class="navbar-inner">  
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">  <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <a class="brand" href="#" style = "margin-left:10px"> MEALS PLANNER </a>
    <div class="nav-collapse collapse">
      <ul class="nav" style = "width:1035px;">
        <li class="<%= active_class('users') %>"><%= link_to('Home', home_path(), :id => "home-nav") %></li>
        <li class="<%= active_class('subscriptions') %>"><%= link_to('My Subscriptions', subscriptions_path, :method => :get, :id => "sub-nav") %></li>
        <li class="<%= active_class('transfers') %>"><%= link_to('My Transfers', transfers_path, :method => :get, :id => "transfer-nav") %></li>
        <li><%= link_to('Transfer Meal', "#", :onclick => 'alert("coming soon")' ) %></li>
        <li class='dropdown' style = "float:right;"> 
          <a class="dropdown-toggle" data-toggle="dropdown" href="#" id="profile-nav"><%= current_user.fullname %>
            <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to('View Profile',"#", :onclick => 'alert("coming soon")') %></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
            </li>
          </ul>
        </li>
      </ul>  
    </div>
  </div>
</div>

app/views/layouts/_welcome.html.erb
<div id = "list">
<h5> Follow these simple steps to subscribe to our meals </h5>
<ol>
	<li> Click on the "Subscribe Now" link </li>
	<li> Choose the month </li>
	<li> Pay the subscription amount </li>
</ol>
<div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Meals Subscription" %></title>
    <link rel="shortcut icon" href="/favicon.icon" />
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="main" role="main">
      <div class="container">  
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <% if user_signed_in? %>  
                <%= render 'layouts/usernavigation' %>
              <% elsif admin_signed_in? %>
                <%= render 'layouts/adminnavigation' %>
              <% end %> 
              <%= yield %>
            </div>
          </div>
          <%= yield :popup %>
        </div>
      </div> 
    </div> 
  </body>
</html>

app/views/layouts/home.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Meals Subscription" %></title>
    <link rel="shortcut icon" href="/favicon.icon" />
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="main" role="main">
      <div class="span7 offset4" id="signin-box">    
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div> 
  </body>
</html>

app/views/layouts/rootpage.html.erb
<div class = "container" >
  <h1>Welcome to the Meals Planner</h1>
  <div class="btn-group">
    <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
      <span class="caret"></span>
    </a>
    <ul class="dropdown-menu">
      <li><%= link_to('Admin',"admins/sign_in", :method => :get) %> </li>
      <li><%= link_to ('Employee',"/users/sign_in", :method => :get) %> </li>
    </ul>
  </div> 
</div>